apiVersion: asdb.aerospike.com/v1alpha1
kind: AerospikeCluster
metadata:
  name: aerospike-cluster
  namespace: aerospike

spec:
  size: 2
  image: aerospike/aerospike-server-enterprise:5.6.0.7

  multiPodPerHost: true

  storage:
    filesystemVolumePolicy:
      cascadeDelete: true
      initMethod: deleteFiles
    volumes:
      - path: /opt/aerospike
        storageClass: ssd
        volumeMode: filesystem
        sizeInGB: 1

  aerospikeAccessControl:
    users:
      - name: admin
        secretName: auth-secret
        roles:
          - sys-admin
          - user-admin
          - read-write

  operatorClientCertSpec:
#    tlsClientName: aerospike-a-0.test-runner
    secretCertSource:
      secretName: "aerospike-secret"
      caCertsFilename: "cacert.pem"
      clientCertFilename: "svc_cluster_chain.pem"
      clientKeyFilename: "svc_key.pem"
#    certPathInOperator:
#      caCertsPath: "/etc/aerospike/secret/cacert.pem"
#      clientCertPath: "/etc/aerospike/secret/svc_cluster_chain.pem"
#      clientKeyPath: "/etc/aerospike/secret/svc_key.pem"

  aerospikeConfigSecret:
    secretName: aerospike-secret
    mountPath:  /etc/aerospike/secret

  aerospikeConfig:
    logging:
      - name: /var/log/aerospike/aerospike.log
        any: detail

    service:
      feature-key-file: /etc/aerospike/secret/features.conf
      os-group-perms: true # 5.6 -

    network:
      service:
        disable-localhost: true # 5.6 -
        tls-name: aerospike-a-0.test-runner
#        tls-authenticate-client: ["aerospike-a-0.test-runner"]
      heartbeat:
        tls-name: aerospike-a-0.test-runner
      fabric:
        tls-name: aerospike-a-0.test-runner
      tls:
        - name: aerospike-a-0.test-runner
          cert-file: /etc/aerospike/secret/svc_cluster_chain.pem
          key-file: /etc/aerospike/secret/svc_key.pem
          ca-file: /etc/aerospike/secret/cacert.pem

    security:
      enable-security: true
      enable-quotas: true # 5.6
      tps-weight: 20 #5.6
      log:
        report-authentication: true # 5.6
        report-sys-admin: true #5.6
        report-user-admin: true #5.6
        report-violation: true #5.6
        report-data-op: ["ns1"] #5.6
        report-data-op-role: ["billing"] #5.6
        report-data-op-user: ["david"] #5.6

      syslog:
        report-authentication: true # 5.6
        report-sys-admin: true #5.6
        report-user-admin: true #5.6
        report-violation: true #5.6
        report-data-op: ["ns1"] #5.6
        report-data-op-role: ["billing"] #5.6
        report-data-op-user: ["david"] #5.6


    namespaces:
      - name: ns1
        memory-size: 1000000000
        replication-factor: 2
        storage-engine:
          type: memory
        sets:
          - name: test1
            disable-eviction: true # 5.6 -
            enable-index: true # 5.6
            stop-writes-count: 10 # 5.6 -

  resources:
    requests:
      memory: 2Gi
      cpu: 200m

  podSpec:
    sidecars:
      - name: aerospike-prometheus-exporter
        image: aerospike/aerospike-prometheus-exporter:1.1.6
        ports:
          - containerPort: 9145
            name: exporter
        env:
          - name: AS_AUTH_USER
            value: admin
          - name: AS_AUTH_PASSWORD
            value: admin123
