apiVersion: v1
kind: ServiceAccount
metadata:
  # Do not change name, its hard-coded in operator
  name: aerospike-cluster
  namespace: aerospike


---
# Role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aerospike-cluster
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - services
  - configmaps
  verbs:
  - get
  - list
- apiGroups:
  - asdb.aerospike.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - '*'

---
# RoleBinding
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aerospike-cluster
roleRef:
  kind: ClusterRole
  name: aerospike-cluster
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: aerospike-cluster
  namespace: aerospike
