apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "asdb.aerospike.com/v1beta1",
          "kind": "AerospikeCluster",
          "metadata": {
            "name": "aerocluster",
            "namespace": "aerospike"
          },
          "spec": {
            "aerospikeAccessControl": {
              "users": [
                {
                  "name": "admin",
                  "roles": [
                    "sys-admin",
                    "user-admin"
                  ],
                  "secretName": "auth-secret"
                }
              ]
            },
            "aerospikeConfig": {
              "logging": [
                {
                  "any": "info",
                  "clustering": "debug",
                  "name": "/var/log/aerospike/aerospike.log"
                }
              ],
              "namespaces": [
                {
                  "memory-size": 3000000000,
                  "name": "test",
                  "replication-factor": 2,
                  "storage-engine": {
                    "type": "memory"
                  }
                }
              ],
              "security": {
                "enable-security": true
              },
              "service": {
                "feature-key-file": "/etc/aerospike/secret/features.conf"
              }
            },
            "image": "aerospike/aerospike-server-enterprise:5.6.0.7",
            "podSpec": {
              "multiPodPerHost": true
            },
            "size": 2,
            "storage": {
              "filesystemVolumePolicy": {
                "cascadeDelete": true,
                "initMethod": "deleteFiles"
              },
              "volumes": [
                {
                  "aerospike": {
                    "path": "/opt/aerospike"
                  },
                  "name": "workdir",
                  "source": {
                    "persistentVolume": {
                      "size": "3Gi",
                      "storageClass": "ssd",
                      "volumeMode": "Filesystem"
                    }
                  }
                },
                {
                  "aerospike": {
                    "path": "/etc/aerospike/secret"
                  },
                  "name": "aerospike-config-secret",
                  "source": {
                    "secret": {
                      "secretName": "aerospike-secret"
                    }
                  }
                }
              ]
            }
          }
        }
      ]
    capabilities: Seamless Upgrades
    categories: Database
    containerImage: docker.io/aerospike/aerospike-kubernetes-operator-nightly:2.0.0-4-dev
    createdAt: 2021-09-15T11:27:51UTC
    description: The Aerospike Kubernetes Operator automates the deployment and management
      of Aerospike enterprise clusters on Kubernetes.
    operators.operatorframework.io/builder: operator-sdk-v1.10.0+git
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
    repository: https://github.com/aerospike/aerospike-kubernetes-operator/
  name: aerospike-kubernetes-operator.v2.0.0-4-dev
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: AerospikeCluster is the schema for the AerospikeCluster API
      displayName: Aerospike Cluster
      kind: AerospikeCluster
      name: aerospikeclusters.asdb.aerospike.com
      version: v1beta1
  description: |
    The Aerospike Kubernetes Operator automates the deployment and management of Aerospike enterprise clusters on Kubernetes. The operator allows you to deploy multi-node Aerospike clusters, recover automatically from node failures, scale up or down automatically as load changes, ensure nodes are evenly split across racks or zones, automatically update to new versions of Aerospike and manage configuration changes in your clusters.

    ### Capabilities:

     -   Deploy Aerospike clusters
     -   Scale up and down existing Aerospike clusters
     -   Version upgrade and downgrade
     -   Configure persistent storage and resource allocation
     -   Standardize and validate configurations
     -   Cluster security management
  displayName: Aerospike Kubernetes operator
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAAKoAAACqBAMAAADPWMmxAAAAGFBMVEX////bNCr41NL86ejzt7PgTkXnc2ztl5Ktf7GpAAAC80lEQVRo3u2aO2/iQBSFP9k86kEYWpsVSWsFTFo7Jmy7hmBaSIzT8gjZv7/FDCRstnCUS4rVnAqJ0aej8T137lgGKysrKysrK6tv0uCzCitAHfVZtSzVUi3VUi3VUi1VkFpcgOo9uheg7pCnenvkqZ0UeWonRp6a+3+tk6AuNNQ9SFIXeq50DpIpKPSim5Vkth71muFKMLGegd5mgn3A2+sV15lgd/FSvaAh2bN07QORINXUPlCXo5radwpJr6b2h6u2oNfCQDPVlvNavJWpmNdj7V8ppcS8ejvdoybKUCW8mkC590rJeTW1f2p8Il47pkzXSsl57Wpo7a3xCXhdnMpUyXk10LPG92WvXQ1tnhG+7PVYqAcl6fWU1ImkV6XUQ/iWVcF6/fDAZLJljoDTqSrUBzrnQRDrWen7aUWuv+qu5WwlvZ4XruC5ZU4D917S6/s8tEXngWMeHmRnF5OHH6JeT9OLrNdTHmS9fjwZpWbt9B8d9+v3guNwMBG+ye8+NnKJ+9Zx6Mpk3zqYPLy7x4jcY00eboXv3DoP8u8H/EtQVSe+BFV56SWoyttfgqq8nX1PaKmWaqmWaqn/LZXxZ5Xab1msrCppFAONsixgVD77wLDcA87rDngtd+A8wcjnd8hVWT5Vom5nQJSXBQT5ug1OVs5j6OeZjzsv5z61FgRxYwpJRaqbd4FoAxDEbg71Kf0ZbMMhkNNfGurBh8SvtgG11hqI9oMQgpgSkhinC9sUcHPqhvrzAUjSQViFWl8GMURK/YLgZdKGrY+bw0gVQN7bbjR1NQUSpTZVqMHzYQlRMfYhmHsxJD5uF7jOYsjUItTUbg4kL+NKe7Caz1unfU23MQRLmm1wiZaQ90I0dZNsKu+r08bNISrGdxDEjRk0O73tEg53yQY313sPQdxsQ/JSqWs3Z3AIibJsAX3fyYGDWoRwpTohPAPUptCPWYf0s2xapbBCcMEdDMwPwO2FADchoJ/46T+9zsrKysrKysrqW/QHHEqsPN3w28oAAAAASUVORK5CYII=
    mediatype: image/webp
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - asdb.aerospike.com
          resources:
          - aerospikeclusters
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - asdb.aerospike.com
          resources:
          - aerospikeclusters/status
          verbs:
          - get
        - apiGroups:
          - asdb.aerospike.com
          resources:
          - aerospikeclusters
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - asdb.aerospike.com
          resources:
          - aerospikeclusters/status
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - statefulsets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - asdb.aerospike.com
          resources:
          - aerospikeclusters
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - asdb.aerospike.com
          resources:
          - aerospikeclusters/finalizers
          verbs:
          - update
        - apiGroups:
          - asdb.aerospike.com
          resources:
          - aerospikeclusters/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - nodes
          verbs:
          - get
          - list
        - apiGroups:
          - ""
          resources:
          - persistentvolumeclaims
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - pods/exec
          verbs:
          - create
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: aerospike-operator-controller-manager
      deployments:
      - name: aerospike-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                  protocol: TCP
                resources: {}
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                image: docker.io/aerospike/aerospike-kubernetes-operator-nightly:2.0.0-4-dev
                imagePullPolicy: Always
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                ports:
                - containerPort: 9443
                  name: webhook-server
                  protocol: TCP
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources: {}
                securityContext:
                  allowPrivilegeEscalation: false
                volumeMounts:
                - mountPath: /tmp/k8s-webhook-server/serving-certs
                  name: cert
                  readOnly: true
              securityContext:
                runAsUser: 65532
              serviceAccountName: aerospike-operator-controller-manager
              terminationGracePeriodSeconds: 10
              volumes:
              - name: cert
                secret:
                  defaultMode: 420
                  secretName: webhook-server-cert
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: aerospike-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - Aerospike
  links:
  - name: Documentation
    url: https://docs.aerospike.com/docs/cloud/kubernetes/operator/index.html
  - name: Aerospike
    url: https://aerospike.com
  maintainers:
  - email: support@aerospike.com
    name: Aerospike, Inc.
  maturity: beta
  provider:
    name: Aerospike
  version: 2.0.0-4-dev
  webhookdefinitions:
  - admissionReviewVersions:
    - v1
    - v1beta1
    containerPort: 443
    deploymentName: aerospike-operator-controller-manager
    failurePolicy: Fail
    generateName: vaerospikecluster.kb.io
    rules:
    - apiGroups:
      - asdb.aerospike.com
      apiVersions:
      - v1beta1
      operations:
      - CREATE
      - UPDATE
      resources:
      - aerospikeclusters
    sideEffects: None
    targetPort: 9443
    type: ValidatingAdmissionWebhook
    webhookPath: /validate-asdb-aerospike-com-v1beta1-aerospikecluster
  - admissionReviewVersions:
    - v1
    - v1beta1
    containerPort: 443
    deploymentName: aerospike-operator-controller-manager
    failurePolicy: Fail
    generateName: maerospikecluster.kb.io
    rules:
    - apiGroups:
      - asdb.aerospike.com
      apiVersions:
      - v1beta1
      operations:
      - CREATE
      - UPDATE
      resources:
      - aerospikeclusters
    sideEffects: None
    targetPort: 9443
    type: MutatingAdmissionWebhook
    webhookPath: /mutate-asdb-aerospike-com-v1beta1-aerospikecluster
