apiVersion: v2
type: application
name: aerospike-restore

# version tracks chart changes
version: 4.0.2
# appVersion tracks operator version
appVersion: 4.0.2

description: A Helm chart for Aerospike Restore Custom Resource
icon: https://avatars0.githubusercontent.com/u/2214313?s=200&v=4

sources:
  - https://github.com/aerospike/aerospike-kubernetes-operator
maintainers:
  - name: Aerospike
    email: developers@aerospike.com
