apiVersion: aerospike.com/v1alpha1
kind: AerospikeCluster
metadata:
  name: aerocluster
  namespace: aerospike
spec:
  # Add fields here
  size: 4
  build: aerospike/aerospike-server-enterprise:4.7.0.10
  #build: aerospike/aerospike-server-enterprise:4.9.0.5
  rack: 
    - ID: 1
      zone: us-central1-a
    - ID: 2
      zone: us-central1-b
  fileStorage: 
    - storageClass: ssd
      volumeMounts:
        - mountPath: /opt/aerospike/data
          sizeInGB: 3
  multiPodPerHost: true 
  aerospikeConfigSecret:
    secretName: aerospike-secret
    mountPath:  /etc/aerospike/secret
  aerospikeConfig:
    service:
      feature-key-file: /etc/aerospike/secret/features.conf
    security:
      enable-security: true
    namespace:
      - name: test
        memory-size: 3000000000
        replication-factor: 2
        storage-engine:
          file: 
            - /opt/aerospike/data/test.dat
          filesize: 2000000000
          data-in-memory: true        
  resources:
    requests: 
      memory: 2Gi
      cpu: 200m
    
