apiVersion: aerospike.com/v1alpha1
kind: AerospikeCluster
metadata:
  name: aerocluster
  namespace: aerospike

spec:
  # Add fields here
  size: 2
  build: aerospike/aerospike-server-enterprise:4.7.0.10

  storage:
    filesystemVolumePolicy:
      cascadeDelete: true
      initMethod: deleteFiles
    blockVolumePolicy:
      cascadeDelete: true
    volumes:
      - storageClass: ssd
        path: /opt/aerospike
        volumeMode: filesystem
        sizeInGB: 1
      - path: /dev/nvme0n1
        storageClass: local-ssd
        volumeMode: block
        sizeInGB: 5
      - path: /dev/sdf
        storageClass: ssd
        volumeMode: block
        sizeInGB: 5

  multiPodPerHost: true

  aerospikeAccessControl:
    users:
      - name: admin
        secretName: auth-secret
        roles:
          - sys-admin
          - user-admin

  aerospikeConfigSecret:
    secretName: aerospike-secret
    mountPath:  /etc/aerospike/secret

  aerospikeConfig:
    service:
      feature-key-file: /etc/aerospike/secret/features.conf
    security:
      enable-security: true
    namespace:
      - name: test
        memory-size: 3000000000
        replication-factor: 2
        storage-engine:
          device:
            - /dev/nvme0n1	/dev/sdf

  resources:
    requests:
      memory: 2Gi
      cpu: 200m
