apiVersion: aerospike.com/v1alpha1
kind: AerospikeCluster
metadata:
  name: aerocluster
  namespace: aerospike
spec:
  # Add fields here
  size: 2
  build: aerospike/aerospike-server-enterprise:4.7.0.10

  fileStorage:
    - storageClass: ssd
      volumeMounts:
        - mountPath: /opt/aerospike/data
          sizeInGB: 3
        - mountPath: /opt/aerospike/xdr
          sizeInGB: 5

  multiPodPerHost: true

  aerospikeAccessControl:
    users:
      admin:
        secretName: auth-secret
        roles:
          - sys-admin
          - user-admin
  aerospikeConfigSecret:
    secretName: aerospike-secret
    mountPath:  /etc/aerospike/secret

  aerospikeConfig:
    logging:
      - name: /var/log/aerospike/aerospike.log
        any: info
    service:
      feature-key-file: /etc/aerospike/secret/features.conf
    security:
      enable-security: true
    xdr:
      enable-xdr: true
      xdr-digestlog-path: /opt/aerospike/xdr/digestlog 5G
      xdr-compression-threshold: 1000
      datacenter:
        - name: REMOTE_DC_1
          dc-node-address-port: "IP PORT"
          dc-security-config-file: /etc/aerospike/secret/security_credentials_DC1.txt
    namespace:
      - name: test
        enable-xdr: true
        xdr-remote-datacenter: REMOTE_DC_1
        memory-size: 3000000000
        replication-factor: 2
        storage-engine:
          file:
            - /opt/aerospike/data/test.dat
          filesize: 2000000000
          data-in-memory: true

  resources:
    requests:
      memory: 5Gi
      cpu: 200m
