apiVersion: aerospike.com/v1alpha1
kind: AerospikeCluster
metadata:
  name: aerocluster
  namespace: aerospike
spec:
  size: 2
  build: aerospike/aerospike-server-enterprise:4.7.0.10

  storage:
    filesystemVolumePolicy:
      cascadeDelete: true
      initMethod: deleteFiles
    volumes:
      - path: /opt/aerospike
        storageClass: ssd
        volumeMode: filesystem
        sizeInGB: 1
      - path: /opt/aerospike/data
        storageClass: ssd
        volumeMode: filesystem
        sizeInGB: 3
      - path: /opt/aerospike/xdr
        storageClass: ssd
        volumeMode: filesystem
        sizeInGB: 3

  multiPodPerHost: true

  aerospikeAccessControl:
    users:
      - name: admin
        secretName: auth-secret
        roles:
          - sys-admin
          - user-admin

  aerospikeConfigSecret:
    secretName: aerospike-secret
    mountPath:  /etc/aerospike/secret

  aerospikeConfig:
    logging:
      - name: /var/log/aerospike/aerospike.log
        any: info
    service:
      feature-key-file: /etc/aerospike/secret/features.conf
    security:
      enable-security: true
    xdr:
      enable-xdr: true
      xdr-digestlog-path: /opt/aerospike/xdr/digestlog 5G
      xdr-compression-threshold: 1000
      datacenter:
        - name: dc1
          dc-node-address-port: "192.168.15.250 8080"
          dc-security-config-file: /etc/aerospike/secret/security_credentials_DC1.txt
    namespace:
      - name: test
        enable-xdr: true
        xdr-remote-datacenter: dc1
        memory-size: 3000000000
        replication-factor: 2
        storage-engine:
          file:
            - /opt/aerospike/data/test.dat
          filesize: 2000000000
          data-in-memory: true

  resources:
    requests:
      memory: 2Gi
      cpu: 200m
