apiVersion: aerospike.com/v1alpha1
kind: AerospikeCluster
metadata:
  name: aeroclusterdst
  namespace: aerospike

spec:
  size: 2
  image: aerospike/aerospike-server-enterprise:4.7.0.10

  storage:
    filesystemVolumePolicy:
      cascadeDelete: true
      initMethod: deleteFiles
    volumes:
      - path: /opt/aerospike
        storageClass: ssd
        volumeMode: filesystem
        sizeInGB: 1
      - path: /opt/aerospike/data
        storageClass: ssd
        volumeMode: filesystem
        sizeInGB: 3

  multiPodPerHost: true

  aerospikeAccessControl:
    users:
      - name: admin
        secretName: auth-secret
        roles:
          - sys-admin
          - user-admin
          - read-write
  aerospikeNetworkPolicy:
    access: "pod"

  aerospikeConfigSecret:
    secretName: aerospike-secret
    mountPath:  /etc/aerospike/secret

  aerospikeConfig:
    service:
      feature-key-file: /etc/aerospike/secret/features.conf
    security:
      enable-security: true
    namespaces:
      - name: test
        memory-size: 3000000000
        replication-factor: 2
        storage-engine:
          files:
            - /opt/aerospike/data/test.dat
          filesize: 2000000000
          data-in-memory: true

  resources:
    requests:
      memory: 2Gi
      cpu: 200m
