{
 "title": "Node Overview",
 "description": "Node Overview dashboard helps visualise multiple nodes in multiple clusters and their metrics with a focus on resources in the nodes.",
 "tags": [
  "node",
  "service",
  "monitoring"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_AEROSPIKE_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job_name",
    "label": "job_name",
    "query": {
     "query": "label_values(aerospike_node_stats_uptime,job)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(aerospike_node_up{job=\"$job_name\"},cluster_name)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(aerospike_node_up{job=\"$job_name\", cluster_name=~\"$cluster|$^\"},service)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(aerospike_namespace_objects{job=\"$job_name\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\" },ns)"
    }
   },
   { "name": "latencytimeunit", "label": "Latency Time Unit", "query": { "query": "metrics(aerospike_latencies_)" } },
   {
    "name": "as_metrics_base_url",
    "query": "https://docs.aerospike.com/reference/metrics"
   },
   {
    "name": "as_configs_base_url",
    "query": "https://docs.aerospike.com/reference/configuration"
   }
  ]
 },
 "panels": [
  {
   "title": "Node List",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "aerospike_node_up{job=\"$job_name\", cluster_name=~\"$cluster|$^\", service=~\"$node|$^\"}"
      }
     ]
    }
   ]
  },
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }, "repeat": "node" },
  {
   "title": "Aerospike Version",
   "type": "stat",
   "description": "Build version of Aerospike Server running on this node",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "count_values by (build) (\"build_numbers\", (aerospike_node_up{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\"}) )",
     "legendFormat": "{{build}}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "piechart",
   "description": "Displays total of all alerts by severity ( critical, error, warn and info) across all the selected node and namespaces",
   "gridPos": { "h": 6, "w": 4, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (severity) (ALERTS{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\", severity=~\"warn|critical|info|error\"}) ",
     "legendFormat": "{{severity}}"
    }
   ]
  },
  {
   "title": "Best Practice",
   "type": "stat",
   "description": "Node failed best practice check, best practice check can be verified using below command in aerospike tools :\n<p><h4>asadm show best-practice</h4></p>",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_node_stats_failed_best_practices{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "description": "Aerospike server running status on this node",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "aerospike_node_up{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\"}",
     "legendFormat": "Aerospike"
    }
   ]
  },
  {
   "title": "Stop Writes / HWM Breached (total)",
   "type": "stat",
   "description": "Displays sum of namespace stop_writes, clock skew stop writes and high water mark breached flags across all the nodes in selected cluster, a positive value means some issue with resource utilization or configurations \n<p>\n<b>More details about these metrics in below links</b></br>\n<a href=\"https://docs.aerospike.com/reference/metrics#stop_writes\" target=\"about:blank\">STOP_WRITES </a> , \n<a target=\"about:blank\" href=\"https://docs.aerospike.com/reference/metrics#clock_skew_stop_writes\">CLOCK_SKEW_STOP_WRITES</a> , \n<a target=\"about:blank\" href=\"https://docs.aerospike.com/reference/metrics#hwm_breached\">HWM_BREACHED</a>\n</p>",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_namespace_stop_writes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Stop Writes"
    },
    {
     "expr": "sum(aerospike_namespace_clock_skew_stop_writes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Clock Skew Stop Writes"
    },
    {
     "expr": "sum(aerospike_namespace_hwm_breached{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "HWM Breached"
    }
   ]
  },
  {
   "title": "Migrations (total)",
   "type": "stat",
   "description": "Displays sum of partitions Remaining and Active which are Received or Transmitted across selected cluster for the selected nodes and namespaces\n<p>\nMore details about the key metrics displayed can be found in below links </br>\n<a target=\"about:blank\" href=\"$as_metrics_base_url#migrate_rx_partitions_remaining\" > RX_PARTITIONS_REMAINING </a> , \n<a target=\"about:blank\" href=\"$as_metrics_base_url#migrate_rx_partitions_active\" > RX_PARTITIONS_ACTIVE </a> ,\n<a target=\"about:blank\" href=\"$as_metrics_base_url#migrate_tx_partitions_remaining\" > TX_PARTITIONS_REMAINING </a>\n<a target=\"about:blank\" href=\"$as_metrics_base_url#migrate_tx_partitions_active\" > TX_PARTITIONS_ACTIVE </a> ,\n\n</p>",
   "gridPos": { "h": 3, "w": 14, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (aerospike_namespace_migrate_rx_partitions_remaining{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})\n\n# topk( 3, sum by (service) (aerospike_namespace_migrate_rx_partitions_remaining{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}))",
     "legendFormat": "RX Remaining"
    },
    {
     "expr": "sum (aerospike_namespace_migrate_rx_partitions_active{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})\n\n# topk( 3, sum by (service) (aerospike_namespace_migrate_tx_partitions_remaining{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}))",
     "legendFormat": "RX Active "
    },
    {
     "expr": "sum (aerospike_namespace_migrate_tx_partitions_remaining{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})\n\n# topk( 3, sum by (service) (aerospike_namespace_migrate_tx_partitions_remaining{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}))",
     "legendFormat": " TX Remaining"
    },
    {
     "expr": "sum (aerospike_namespace_migrate_tx_partitions_active{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})\n\n# topk( 3, sum by (service) (aerospike_namespace_migrate_tx_partitions_remaining{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}))",
     "legendFormat": " TX Active"
    }
   ]
  },
  {
   "title": "Data (bytes) (total)",
   "type": "stat",
   "description": "Displays sum of all device or memory used by data (without index) and the sum of allocated bytes",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_namespace_device_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} or aerospike_namespace_pmem_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"}\n) ",
     "legendFormat": "Used (Device/PMEM) (pre 7x)"
    },
    {
     "expr": "sum(aerospike_namespace_data_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} )",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(aerospike_namespace_device_total_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_pmem_total_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(aerospike_namespace_data_total_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Index used (bytes) (total)",
   "type": "stat",
   "description": "Displays sum of all device or memory used by index, sindex and set-index",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\naerospike_namespace_memory_used_index_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_memory_used_sindex_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_memory_used_set_index_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_index_pmem_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_sindex_pmem_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\n)",
     "legendFormat": "Used Bytes"
    },
    {
     "expr": "sum(\naerospike_namespace_index_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_sindex_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_set_index_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\n)",
     "legendFormat": "Used Bytes"
    }
   ]
  },
  {
   "title": "Index (Flash) alloc (bytes) (total)",
   "type": "stat",
   "description": "Flash Alloc Bytes - Total bytes allocated on the mount(s) for the primary index used by this namespace on this node. This statistic represents entire 4KiB chunks which have at least one element in use.\n\n\nFlash Alloc Percent - Percentage of the mount(s) allocated for the primary index used by this namespace on this node. Calculated as (index_flash_alloc_bytes / index-type.mounts-size-limit) * 100. This statistic represents entire 4KiB chunks which have at least one element in use.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_namespace_index_flash_alloc_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Allocated Bytes"
    }
   ]
  },
  {
   "title": "Master Objects (total)",
   "type": "stat",
   "description": "Total of records in the namespace across all the selected nodes\n<p>\n<b>More details can be found about the key metrics/confings using below links </b> </br>\n<a target=\"about:blank\" href=\"$as_metrics_base_url#master_objects\">MASTER OBJECTS </a> ,\n</p>",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_namespace_master_objects{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Min"
    }
   ]
  },
  {
   "title": "Data used (bytes)",
   "type": "bargauge",
   "description": "Displays minimum, average and maximum of all device or memory used by data (without index) across all namespaces",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(aerospike_namespace_device_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} or \naerospike_namespace_pmem_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(aerospike_namespace_device_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} or \naerospike_namespace_pmem_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(aerospike_namespace_device_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} or \naerospike_namespace_pmem_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Max"
    },
    {
     "expr": "min(aerospike_namespace_data_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} )",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(aerospike_namespace_data_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} )",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(aerospike_namespace_data_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} )",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "% Data used",
   "type": "bargauge",
   "description": "Displays minimum , average  and maximum  device or memory used % by data (without index) ",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min( (100-aerospike_namespace_pmem_free_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} ) or (100-aerospike_namespace_device_free_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} )\n)",
     "legendFormat": "Min. Device/PMEM"
    },
    {
     "expr": "avg( (100-aerospike_namespace_pmem_free_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} ) or (100-aerospike_namespace_device_free_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} )\n)",
     "legendFormat": "Avg. Device/PMEM"
    },
    {
     "expr": "avg( (100-aerospike_namespace_pmem_free_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} ) or (100-aerospike_namespace_device_free_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} )\n)",
     "legendFormat": "Max. Device/PMEM"
    },
    {
     "expr": "min( (aerospike_namespace_data_used_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} ) \n)",
     "legendFormat": "Min"
    },
    {
     "expr": "avg( (aerospike_namespace_data_used_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} ) \n)",
     "legendFormat": "Avg"
    },
    {
     "expr": "Max( (aerospike_namespace_data_used_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} ) \n)",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Index used (bytes)",
   "type": "bargauge",
   "description": "Displays minimum, average and maximum device or memory used by index, sindex and set-index across all namespaces",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(\naerospike_namespace_memory_used_index_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_memory_used_sindex_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_memory_used_set_index_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_index_pmem_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_sindex_pmem_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\n)",
     "legendFormat": "Min. "
    },
    {
     "expr": "avg(\naerospike_namespace_memory_used_index_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_memory_used_sindex_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_memory_used_set_index_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_index_pmem_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_sindex_pmem_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\n)",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(\naerospike_namespace_memory_used_index_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_memory_used_sindex_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_memory_used_set_index_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_index_pmem_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_sindex_pmem_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\n)",
     "legendFormat": "Max"
    },
    {
     "expr": "min(\naerospike_namespace_index_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_sindex_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_set_index_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\n)",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(\naerospike_namespace_index_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_sindex_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_set_index_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\n)",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(\naerospike_namespace_index_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_sindex_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\nor\naerospike_namespace_set_index_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}\n)",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Index (Flash) alloc (bytes)",
   "type": "bargauge",
   "description": "Flash Alloc Bytes - Total bytes allocated on the mount(s) for the primary index used by this namespace on this node. This statistic represents entire 4KiB chunks which have at least one element in use.\n\n\nFlash Alloc Percent - Percentage of the mount(s) allocated for the primary index used by this namespace on this node. Calculated as (index_flash_alloc_bytes / index-type.mounts-size-limit) * 100. This statistic represents entire 4KiB chunks which have at least one element in use.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(aerospike_namespace_index_flash_alloc_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(aerospike_namespace_index_flash_alloc_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(aerospike_namespace_index_flash_alloc_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Master Objects",
   "type": "bargauge",
   "description": "Displays Minimum, Average and Maximum records in the namespace across all the selected nodes\n<p>\n<b>More details can be found about the key metrics/confings using below links </b> </br>\n<a target=\"about:blank\" href=\"$as_metrics_base_url#master_objects\">MASTER OBJECTS </a> ,\n</p>",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(aerospike_namespace_master_objects{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(aerospike_namespace_master_objects{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Avg."
    },
    {
     "expr": "max(aerospike_namespace_master_objects{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "% Set Quota used (topk)",
   "type": "bargauge",
   "description": "Display Quota usage of top 3 SET's in selected namespace against \"stop write size\" configuration defined for the set\n<pre>\n6.x Formula: ((memory_data_bytes + device_data_bytes)/ stop_writes_size)*100 \nOR\n((data_used_bytes)/ stop_writes_size)*100\n</pre>\n<p>\n<b>More details can be found key metrics and configs using below links</b> </br>\n<a target=\"about:blank\" href=\"$as_metrics_base_url#memory_data_bytes\" >MEMORY_DATA_BYTES</a> , \n<a target=\"about:blank\" href=\"$as_metrics_base_url#device_data_bytes\" >DEVICE_DATA_BYTES</a> , \n<a target=\"about:blank\" href=\"$as_configs_base_url#stop-writes-size\" >STOP_WRITES_SIZE</a> , \n<a target=\"about:blank\" href=\"$as_metrics_base_url#data_used_bytes\" >DATA_USED_BYTES</a> , \n</p>",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(3,sort_desc((\n  (aerospike_sets_memory_data_bytes{job=\"$job_name\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}+aerospike_sets_device_data_bytes{job=\"$job_name\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})\n  /(aerospike_sets_stop_writes_size{job=\"$job_name\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}!=0) )*100))",
     "legendFormat": "{{ns}}/{{set}}"
    },
    {
     "expr": "topk( 3, (\n  (aerospike_sets_data_used_bytes{job=\"$job_name\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})\n  /(aerospike_sets_stop_writes_size{job=\"$job_name\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}!=0) )*100) ",
     "legendFormat": "{{ns}}/{{set}}"
    }
   ]
  },
  {
   "title": "6.x Data (Memory) (deprecated) (bytes) (total)",
   "type": "stat",
   "description": "Displays sum of storage memory used by data (without index) across all the namespaces, \n<pre>\nNOTE: this panel is deprecated from 7.0 onwards as this metric is merged into common data metrics\n</pre>",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_namespace_memory_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} unless (aerospike_namespace_device_total_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"} or aerospike_namespace_pmem_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"} ) )",
     "legendFormat": "Used"
    },
    {
     "expr": "sum(aerospike_namespace_memory_size{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"}\nunless (aerospike_namespace_device_total_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"} or aerospike_namespace_pmem_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"} )\n)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Connections (total)",
   "type": "stat",
   "description": "Total Client/Heartbeat/Fabric connections count across all the selected nodes\n<p>\n<b>More details about the key metrics / configs can be found using below links </b></br>\n<a target=\"about:blank\" href=\"$as_metrics_base_url#client_connections\">CLIENT CONNECTIONS </a> ,\n<a target=\"about:blank\" href=\"$as_metrics_base_url#heartbeat_connections\">HEARTBEAT CONNECTIONS </a> ,\n<a target=\"about:blank\" href=\"$as_metrics_base_url#fabric_connections\">FABRIC CONNECTIONS </a> ,\n</p>",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(aerospike_node_stats_client_connections{job=\"$job_name\", cluster_name=~\"$cluster\"})",
     "legendFormat": "Client"
    },
    {
     "expr": "sum(aerospike_node_stats_heartbeat_connections{job=\"$job_name\", cluster_name=~\"$cluster\"})",
     "legendFormat": "Heartbeat"
    },
    {
     "expr": "sum(aerospike_node_stats_fabric_connections{job=\"$job_name\", cluster_name=~\"$cluster\"})",
     "legendFormat": "Fabric"
    }
   ]
  },
  {
   "title": "6.x % Memory free (deprecated)",
   "type": "bargauge",
   "description": "Displays minimuim, average and maximum memory available for storage across all the namespaces, \n<pre>\nNOTE: this panel is deprecated from 7.0 onwards as this metric is merged into common data metrics\n</pre>",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(aerospike_namespace_memory_free_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"}\nunless (aerospike_namespace_device_total_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"} or aerospike_namespace_pmem_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"} )\n)",
     "legendFormat": "Min"
    },
    {
     "expr": "avg(aerospike_namespace_memory_free_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"}\nunless (aerospike_namespace_device_total_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"} or aerospike_namespace_pmem_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"} )\n)",
     "legendFormat": "Avg"
    },
    {
     "expr": "max(aerospike_namespace_memory_free_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"}\nunless (aerospike_namespace_device_total_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"} or aerospike_namespace_pmem_used_bytes{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"} )\n)",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "description": "Client connections, fabric connections and heartbeat connections",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aerospike_node_stats_client_connections{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\"}",
     "legendFormat": "{{service}} : Client"
    },
    {
     "expr": "aerospike_node_stats_fabric_connections{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\"}",
     "legendFormat": "{{service}} : Fabric"
    },
    {
     "expr": "aerospike_node_stats_heartbeat_connections{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\"}",
     "legendFormat": "{{service}} : Heartbeat"
    }
   ]
  },
  {
   "title": "% Data (topk)",
   "type": "timeseries",
   "description": "Percentage of storage available for further use",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "\n( \n    (100-aerospike_namespace_memory_free_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"})\n    unless ( \n        aerospike_namespace_device_free_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} \n        or aerospike_namespace_pmem_free_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"} \n        ) \n    or\n    (100-aerospike_namespace_device_free_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"})\n    or\n    (100-aerospike_namespace_pmem_free_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"})\n)\n",
     "legendFormat": "{{service}}/{{ns}} : Used"
    },
    {
     "expr": "(aerospike_namespace_data_used_pct{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"})",
     "legendFormat": "{{service}}/{{ns}} : Used"
    }
   ]
  },
  {
   "title": "Connections Opened / Closed (rate)",
   "type": "timeseries",
   "description": "Rate of client, heartbeat and fabric connections opened or closed",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(aerospike_node_stats_client_connections_opened{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\"}[$__rate_interval])",
     "legendFormat": "{{service}} : Client Opened"
    },
    {
     "expr": "rate(aerospike_node_stats_client_connections_closed{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\"}[$__rate_interval])",
     "legendFormat": "{{service}} : Client Closed"
    },
    {
     "expr": "rate(aerospike_node_stats_fabric_connections_opened{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\"}[$__rate_interval])",
     "legendFormat": "{{service}} :  Fabric Opened"
    },
    {
     "expr": "rate(aerospike_node_stats_fabric_connections_closed{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\"}[$__rate_interval])",
     "legendFormat": "{{service}} :  Fabric Closed"
    },
    {
     "expr": "rate(aerospike_node_stats_heartbeat_connections_opened{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\"}[$__rate_interval])",
     "legendFormat": "{{service}} : Heartbeat Opened"
    },
    {
     "expr": "rate(aerospike_node_stats_heartbeat_connections_closed{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\"}[$__rate_interval])",
     "legendFormat": "{{service}} : Heartbeat Closed"
    }
   ]
  },
  {
   "title": "Latency: Reads / sec (max)",
   "type": "timeseries",
   "description": "Reads per second",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(aerospike_latencies_read_${latencytimeunit}_bucket{job=\"$job_name\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\", le=~\"[0-9]*\"}) by (le)",
     "legendFormat": "<={{le}}${latencytimeunit}"
    },
    {
     "expr": "max(aerospike_latencies_read_${latencytimeunit}_count{job=\"$job_name\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Ops/sec"
    }
   ]
  },
  {
   "title": "Client Writes (TPS) (rate) (total)",
   "type": "timeseries",
   "description": "Shows per-second average rate of increase in\n\n1. Total writes = client_write_success + client_write_error + client_write_timeout + batch_sub_write_success + batch_sub_write_error + batch_sub_write_timeout\n2. Successful writes = client_write_success + batch_sub_write_success\n3. Errored writes = client_write_error + batch_sub_write_error\n4. Timedout writes = client_write_timeout + batch_sub_write_timeout",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (job, cluster_name, service) (rate(aerospike_namespace_client_write_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])+rate(aerospike_namespace_client_write_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval])+rate(aerospike_namespace_client_write_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_write_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_write_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_write_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]))",
     "legendFormat": "{{service}} : Total"
    },
    {
     "expr": "sum by (job, cluster_name, service) (rate(aerospike_namespace_client_write_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_write_success{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]))",
     "legendFormat": "{{service}} : Successful"
    },
    {
     "expr": "sum by (job, cluster_name, service) (rate(aerospike_namespace_client_write_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_write_timeout{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]))",
     "legendFormat": "{{service}}: Timeout"
    },
    {
     "expr": "sum by (job, cluster_name, service) (rate(aerospike_namespace_client_write_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]) + rate(aerospike_namespace_batch_sub_write_error{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}[$__rate_interval]))",
     "legendFormat": "{{service}}: Error"
    }
   ]
  },
  {
   "title": "Latency: Writes / sec (max)",
   "type": "timeseries",
   "description": "Writes per second",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(aerospike_latencies_write_${latencytimeunit}_bucket{job=\"$job_name\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\", le=~\"[0-9]*\"}) by (le)",
     "legendFormat": "<={{le}}${latencytimeunit}"
    },
    {
     "expr": "max(aerospike_latencies_write_${latencytimeunit}_count{job=\"$job_name\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Ops/sec"
    }
   ]
  },
  {
   "title": "% Set Quota used by Namespace",
   "type": "timeseries",
   "description": "% of quota used by each set by a namespace within this node",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "\n  (\n  (aerospike_sets_memory_data_bytes{job=\"$job_name\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}+aerospike_sets_device_data_bytes{job=\"$job_name\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})\n  /(aerospike_sets_stop_writes_size{job=\"$job_name\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}!=0) )*100",
     "legendFormat": "{{service}}/{{ns}} : {{set}}"
    },
    {
     "expr": "\n  (\n  (aerospike_sets_data_used_bytes{job=\"$job_name\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})\n  /(aerospike_sets_stop_writes_size{job=\"$job_name\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}!=0) )*100",
     "legendFormat": "{{service}}/{{ns}} : {{set}}"
    }
   ]
  },
  {
   "title": "Latency: Sindex Query / sec (max)",
   "type": "timeseries",
   "description": "Secondary index queries per second",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(aerospike_latencies_si_query_${latencytimeunit}_bucket{job=\"$job_name\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\", le=~\"[0-9]*\"}) by (le)",
     "legendFormat": "<={{le}}${latencytimeunit}"
    },
    {
     "expr": "max(aerospike_latencies_si_query_${latencytimeunit}_count{job=\"$job_name\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Ops/sec"
    }
   ]
  },
  {
   "title": "Objects",
   "type": "timeseries",
   "description": "Master objects, prole objects and tombstones",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aerospike_namespace_master_objects{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
     "legendFormat": "{{service}}/{{ns}} : Master"
    },
    {
     "expr": "aerospike_namespace_prole_objects{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
     "legendFormat": "{{service}}/{{ns}} : Prole"
    },
    {
     "expr": "aerospike_namespace_tombstones{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
     "legendFormat": "{{service}}/{{ns}} : Tombstones"
    }
   ]
  },
  {
   "title": "Latency: UDF / sec (max)",
   "type": "timeseries",
   "description": "UDF transactions per second",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(aerospike_latencies_udf_${latencytimeunit}_bucket{job=\"$job_name\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\", le=~\"[0-9]*\"}) by (le)",
     "legendFormat": "<={{le}}${latencytimeunit}"
    },
    {
     "expr": "max(aerospike_latencies_udf_${latencytimeunit}_count{job=\"$job_name\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Ops/sec"
    }
   ]
  },
  {
   "title": "Migrations (Partitions)",
   "type": "timeseries",
   "description": "Migrations remaining migrate_tx_partitions_remaining (transmit), migrate_rx_partitions_remaining (receive)",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(aerospike_namespace_migrate_rx_partitions_remaining{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\", ns=~\"$namespace|$^\"})",
     "legendFormat": "{{service}}/{{ns}} : Incoming "
    },
    {
     "expr": " (aerospike_namespace_migrate_tx_partitions_remaining{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node\",  ns=~\"$namespace|$^\"})",
     "legendFormat": "{{service}}/{{ns}} : Outgoing "
    },
    {
     "expr": " (aerospike_namespace_migrate_rx_partitions_active{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "{{service}}/{{ns}} : RX Active"
    },
    {
     "expr": "(aerospike_namespace_migrate_tx_partitions_active{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "{{service}}/{{ns}} : TX Active "
    }
   ]
  },
  {
   "title": "Latency: Pindex Query / sec (max)",
   "type": "timeseries",
   "description": "Primary index queries per second",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(aerospike_latencies_pi_query_${latencytimeunit}_bucket{job=\"$job_name\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\", le=~\"[0-9]*\"}) by (le)",
     "legendFormat": "<={{le}}${latencytimeunit}"
    },
    {
     "expr": "max(aerospike_latencies_pi_query_${latencytimeunit}_count{job=\"$job_name\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Ops/sec"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "description": "Number of detached server threads currently running.\n\nNumber of joinable server threads currently running.\n\nNumber of currently active threads in the server thread pool.\n\nTotal number of threads in the server thread pool.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aerospike_node_stats_threads_detached{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
     "legendFormat": "{{service}} : Detached"
    },
    {
     "expr": "aerospike_node_stats_threads_joinable{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
     "legendFormat": "{{service}} : Joinable"
    },
    {
     "expr": "aerospike_node_stats_threads_pool_active{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
     "legendFormat": "{{service}} : Active (server thread pool)"
    },
    {
     "expr": "aerospike_node_stats_threads_pool_total{job=\"$job_name\", cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"}",
     "legendFormat": "{{service}} : Total (server thread pool)"
    }
   ]
  },
  {
   "title": "Latency: Proxies / sec (max)",
   "type": "timeseries",
   "description": "Proxies per second",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(aerospike_latencies_proxy_${latencytimeunit}_bucket{job=\"$job_name\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\", le=~\"[0-9]*\"}) by (le)",
     "legendFormat": "<={{le}}${latencytimeunit}"
    },
    {
     "expr": "max(aerospike_latencies_proxy_${latencytimeunit}_count{job=\"$job_name\",cluster_name=~\"$cluster\", service=~\"$node|$^\", ns=~\"$namespace|$^\"})",
     "legendFormat": "Ops/sec"
    }
   ]
  }
 ]
}