apiVersion: asdb.aerospike.com/v1
kind: AerospikeCluster
metadata:
  name: {{ template "aerospike-cluster.commonName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "aerospike-cluster.commonName" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    {{- with .Values.customLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

spec:
  # Aerospike cluster size
  size: {{ .Values.replicas }}

  # Aerospike server docker image
  image: {{ .Values.image.repository | default "aerospike/aerospike-server-enterprise" }}:{{ .Values.image.tag | default "8.0.0.0" }}

  ## maxUnavailable defines percentage/number of pods that can be allowed to go down or unavailable
  ## before application disruption.
  maxUnavailable: {{ .Values.maxUnavailable }}

  ## Disable the PodDisruptionBudget creation for the Aerospike cluster.
  disablePDB: {{ .Values.disablePDB }}

  # Aerospike access control configuration
  {{- with .Values.aerospikeAccessControl }}
  aerospikeAccessControl: {{- toYaml . | nindent 4 }}
  {{- end }}

  # Aerospike configuration
  {{- with .Values.aerospikeConfig }}
  aerospikeConfig: {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- if and .Values.devMode (not .Values.aerospikeConfig) }}
  aerospikeConfig:
    service:
      feature-key-file: /etc/aerospike/secrets/features.conf

    network:
      service:
        port: 3000
      fabric:
        port: 3001
      heartbeat:
        port: 3002

    namespaces:
      - name: test
        replication-factor: 2
        storage-engine:
          type: memory
          data-size: 1073741824 # 1GiB

  {{- end }}

  ## enableDynamicConfigUpdate enables dynamic config update flow of the operator.
  enableDynamicConfigUpdate: {{ .Values.enableDynamicConfigUpdate }}

  # Aerospike network policy
  {{- with .Values.aerospikeNetworkPolicy }}
  aerospikeNetworkPolicy: {{- toYaml . | nindent 4 }}
  {{- end }}

  # Aerospike pod spec
  {{- with .Values.podSpec }}
  podSpec: {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- if and .Values.devMode (not .Values.podSpec) }}
  podSpec:
    multiPodPerHost: true
  {{- end }}

  # Rack configuration
  {{- with .Values.rackConfig }}
  rackConfig: {{- toYaml . | nindent 4 }}
  {{- end }}

  # Storage configuration
  {{- with .Values.storage }}
  storage: {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- if and .Values.devMode (not .Values.storage) }}
  storage:
    volumes:
    - name: aerospike-config-secret
      source:
        secret:
          secretName: aerospike-secret
      aerospike:
        path: /etc/aerospike/secrets
  {{- end }}

  # Validation policy
  {{- with .Values.validationPolicy }}
  validationPolicy: {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- if and .Values.devMode (not .Values.validationPolicy) }}
  validationPolicy:
    skipWorkDirValidate: true
    skipXdrDlogFileValidate: true
  {{- end }}

  # operatorClientCert defines certificates to connect to Aerospike
  {{- with .Values.operatorClientCert }}
  operatorClientCert: {{- toYaml . | nindent 4 }}
  {{- end }}

  # seedsFinderServices defines service (e.g. loadbalancer) to connect to Aerospike
  {{- with .Values.seedsFinderServices }}
  seedsFinderServices: {{- toYaml . | nindent 4 }}
  {{- end }}

  ## rosterNodeBlockList is a list of blocked nodeIDs from roster in a strong-consistency setup
  {{- with .Values.rosterNodeBlockList }}
  rosterNodeBlockList: {{- toYaml . | nindent 4 }}
  {{- end }}

  ## k8sNodeBlockList is a list of Kubernetes nodes which are not used for Aerospike pods.
  {{- with .Values.k8sNodeBlockList }}
  k8sNodeBlockList: {{- toYaml . | nindent 4 }}
  {{- end }}

  ## operations is a list of on-demand operations to be performed on the Aerospike cluster.
  {{- with .Values.operations }}
  operations: {{- toYaml . | nindent 4 }}
  {{- end }}

  ## Pause reconciliation of the cluster
  paused: {{ .Values.paused }}
