apiVersion: asdb.aerospike.com/v1beta1
kind: AerospikeCluster
metadata:
  name: {{ template "aerospike-cluster.commonName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "aerospike-cluster.commonName" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  # Aerospike cluster size
  size: {{ .Values.replicas | default 3 }}

  # Aerospike server docker image
  image: {{ .Values.image.repository | default "aerospike/aerospike-server-enterprise" }}:{{ .Values.image.tag | default "5.7.0.8" }}

  # Aerospike access control configuration
  {{- with .Values.aerospikeAccessControl }}
  aerospikeAccessControl: {{- toYaml . | nindent 4 }}
  {{- end }}

  # Aerospike configuration
  {{- with .Values.aerospikeConfig }}
  aerospikeConfig: {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- if and .Values.devMode (not .Values.aerospikeConfig) }}
  aerospikeConfig:
    service:
      feature-key-file: /etc/aerospike/secrets/features.conf

    network:
      service:
        port: 3000
      fabric:
        port: 3001
      heartbeat:
        port: 3002

    namespaces:
      - name: test
        memory-size: 1073741824 # 1GiB
        replication-factor: 2
        storage-engine:
          type: memory
  {{- end }}

  # Aerospike network policy
  {{- with .Values.aerospikeNetworkPolicy }}
  aerospikeNetworkPolicy: {{- toYaml . | nindent 4 }}
  {{- end }}

  # Aerospike pod spec
  {{- with .Values.podSpec }}
  podSpec: {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- if and .Values.devMode (not .Values.podSpec) }}
  podSpec:
    multiPodPerHost: true
  {{- end }}

  # Rack configuration
  {{- with .Values.rackConfig }}
  rackConfig: {{- toYaml . | nindent 4 }}
  {{- end }}

  # Storage configuration
  {{- with .Values.storage }}
  storage: {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- if and .Values.devMode (not .Values.storage) }}
  storage:
    volumes:
    - name: aerospike-config-secret
      source:
        secret:
          secretName: aerospike-license
      aerospike:
        path: /etc/aerospike/secrets
  {{- end }}

  # Validation policy
  {{- with .Values.validationPolicy }}
  validationPolicy: {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- if and .Values.devMode (not .Values.validationPolicy) }}
  validationPolicy:
    skipWorkDirValidate: true
    skipXdrDlogFileValidate: true
  {{- end }}

  # operatorClientCert defines certificates to connect to Aerospike
  {{- with .Values.operatorClientCert }}
  operatorClientCert: {{- toYaml . | nindent 4 }}
  {{- end }}

  # seedsFinderServices defines service (e.g. loadbalancer) to connect to Aerospike
  {{- with .Values.seedsFinderServices }}
  seedsFinderServices: {{- toYaml . | nindent 4 }}
  {{- end }}
