apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "aerospike-cluster.commonName" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
type: Opaque
data:
  {{- if (.Values.featureKeyFile) }}
  features.conf: {{ .Values.featureKeyFile | b64enc | quote }}
  {{- end }}

  {{- with .Values.secrets }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
