apiVersion: v1
kind: Service
metadata:
  name: aerospike-monitoring-stack-grafana
  namespace: monitoring
  labels:
    app: aerospike-monitoring-stack-grafana
    chart: aerospike-monitoring-stack
    release: aerospike-monitoring-stack
    app.kubernetes.io/component: grafana
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: aerospike-monitoring-stack-grafana