apiVersion: asdb.aerospike.com/v1beta1
kind: AerospikeRestore
metadata:
  labels:
    app.kubernetes.io/name: aerospikerestore
    app.kubernetes.io/instance: aerospikerestore-sample
    app.kubernetes.io/part-of: aerospike-kubernetes-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: aerospike-kubernetes-operator
  name: aerospikerestore-sample
spec:
  backupService:
    name: aerospikebackupservice-sample
    namespace: aerospike
  type: Full
  config:
    destination:
      label: destinationCluster
      credentials:
        password: admin123
        user: admin
      seed-nodes:
        - host-name: aerocluster.test.svc.cluster.local
          port: 3000
    policy:
      parallel: 3
      no-generation: true
      no-indexes: true
    source:
      "path": "/localStorage/test-routine/backup/1719824240816/data/test"
      "type": 0

