apiVersion: asdb.aerospike.com/v1beta1
kind: AerospikeBackup
metadata:
  labels:
    app.kubernetes.io/name: aerospikebackup
    app.kubernetes.io/instance: aerospikebackup-sample
    app.kubernetes.io/part-of: aerospike-kubernetes-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: aerospike-kubernetes-operator
  name: aerospikebackup-sample
spec:
  backupService:
    name: aerospikebackupservice-sample
    namespace: aerospike
  onDemand:
    id: first-ad-hoc-backup
    routineName: test-routine
  config:
    aerospike-cluster:
      test-cluster:
        credentials:
          password: admin123
          user: admin
        seed-nodes:
          - host-name: aerocluster.aerospike.svc.cluster.local
            port: 3000
    backup-routines:
      test-routine:
        backup-policy: test-policy
        interval-cron: "@daily"
        incr-interval-cron: "@hourly"
        namespaces: ["test"]
        source-cluster: test-cluster
        storage: local
