# This is a simple example for demonstration only, that launches an in-memory,
# non-secure Aerospike cluster, with no dependencies other than an Aerospike
# license secret. This is not recommended for production use.
# Visit https://docs.aerospike.com/cloud/kubernetes/operator for details.
#
# Before creating this cluster,
# - Prepare the aerospike namespace by following instruction here
#
# https://docs.aerospike.com/cloud/kubernetes/operator/create-cluster-kubectl#prepare-the-namespace
#
# - Create the Kubernetes secret containing the Aerospike features.conf file as follows:
#
# kubectl create secret generic aerospike-secret --from-file=<path-of-features.conf> -n aerospike

apiVersion: asdb.aerospike.com/v1
kind: AerospikeCluster
metadata:
  name: aerocluster
  namespace: aerospike

spec:
  size: 2
  image: aerospike/aerospike-server-enterprise:6.4.0.0
  podSpec:
    multiPodPerHost: true

  validationPolicy:
    skipWorkDirValidate: true
    skipXdrDlogFileValidate: true

  storage:
    volumes:
      - name: aerospike-config-secret
        source:
          secret:
            secretName: aerospike-secret
        aerospike:
          path: /etc/aerospike/secret

  aerospikeConfig:
    service:
      feature-key-file: /etc/aerospike/secret/features.conf
    network:
      service:
        port: 3000
      fabric:
        port: 3001
      heartbeat:
        port: 3002
    namespaces:
      - name: test
        memory-size: 3000000000
        replication-factor: 2
        storage-engine:
          type: memory
