{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aerospike-operator-aerospikerestore-viewer-role
  labels:
    app: {{ template "aerospike-kubernetes-operator.fullname" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
rules:
- apiGroups:
  - asdb.aerospike.com
  resources:
  - aerospikerestores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - asdb.aerospike.com
  resources:
  - aerospikerestores/status
  verbs:
  - get
{{- end }}
