{{- range $key, $ns := (split "," .Values.watchNamespaces) }}

# Service account used by the cluster pods to obtain pod metadata.
apiVersion: v1
kind: ServiceAccount
metadata:
  # Do not change name, it's hard-coded in operator
  name: aerospike-operator-controller-manager
  namespace: "{{ $ns }}"
  labels:
    app: {{ template "aerospike-kubernetes-operator.fullname" $ }}
    chart: {{ $.Chart.Name }}
    release: {{ $.Release.Name }}
{{- with $.Values.imagePullSecrets }}
imagePullSecrets:
  {{- range . }}
  - name: {{ . }}
  {{- end }}
{{- end }}
---

# Role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aerospike-cluster-{{ $ns }}-{{ $.Release.Name }}
  labels:
    app: {{ template "aerospike-kubernetes-operator.fullname" $ }}
    chart: {{ $.Chart.Name }}
    release: {{ $.Release.Name }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - services
  - configmaps
  verbs:
  - get
  - list
- apiGroups:
  - asdb.aerospike.com
  resources:
  - '*'
  verbs:
  - '*'
---

# RoleBinding
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aerospike-cluster-{{ $ns }}-{{ $.Release.Name }}
  labels:
    app: {{ template "aerospike-kubernetes-operator.fullname" $ }}
    chart: {{ $.Chart.Name }}
    release: {{ $.Release.Name }}
roleRef:
  kind: ClusterRole
  name: aerospike-cluster-{{ $ns }}-{{ $.Release.Name }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: aerospike-operator-controller-manager
  namespace: {{ $ns }}
---
{{- end }}
