apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aerospike-cluster
  labels:
    app: {{ template "aerospike-kubernetes-operator.fullname" $ }}
    chart: {{ $.Chart.Name }}
    release: {{ $.Release.Name }}
rules:
- apiGroups:
    - ""
  resources:
    - pods
    - nodes
    - services
    - configmaps
    - persistentvolumeclaims
  verbs:
    - get
    - list
- apiGroups:
    - asdb.aerospike.com
  resources:
    - '*'
  verbs:
    - '*'
