apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/aerospike-operator-serving-cert
  name: aerospike-operator-mutating-webhook-configuration
  labels:
    app: {{ template "aerospike-kubernetes-operator.fullname" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: aerospike-operator-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-asdb-aerospike-com-v1-aerospikecluster
  failurePolicy: Fail
  {{- if .Values.watchNamespaces }}
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
        {{- range splitList "," .Values.watchNamespaces }}
          - {{ . | trim | quote }}
        {{- end }}
    {{- end }}
  name: maerospikecluster.kb.io
  rules:
  - apiGroups:
    - asdb.aerospike.com
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - aerospikeclusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: aerospike-operator-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-asdb-aerospike-com-v1beta1-aerospikebackupservice
  failurePolicy: Fail
  {{- if .Values.watchNamespaces }}
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
        {{- range splitList "," .Values.watchNamespaces }}
          - {{ . | trim | quote }}
        {{- end }}
    {{- end }}
  name: maerospikebackupservice.kb.io
  rules:
  - apiGroups:
    - asdb.aerospike.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - aerospikebackupservices
  sideEffects: None
- admissionReviewVersions:
    - v1
  clientConfig:
    service:
      name: aerospike-operator-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /mutate-asdb-aerospike-com-v1beta1-aerospikerestore
  failurePolicy: Fail
  {{- if .Values.watchNamespaces }}
  namespaceSelector:
    matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: In
        values:
        {{- range splitList "," .Values.watchNamespaces }}
          - {{ . | trim | quote }}
        {{- end }}
    {{- end }}
  name: maerospikerestore.kb.io
  rules:
  - apiGroups:
    - asdb.aerospike.com
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - aerospikerestores
  sideEffects: None
