{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aerospike-operator-proxy-rolebinding
  labels:
    app: {{ template "aerospike-kubernetes-operator.fullname" . }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aerospike-operator-proxy-role
subjects:
- kind: ServiceAccount
  name: {{ template "aerospike-kubernetes-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
