//go:build !ignore_autogenerated

/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AerospikeBackup) DeepCopyInto(out *AerospikeBackup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AerospikeBackup.
func (in *AerospikeBackup) DeepCopy() *AerospikeBackup {
	if in == nil {
		return nil
	}
	out := new(AerospikeBackup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AerospikeBackup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AerospikeBackupList) DeepCopyInto(out *AerospikeBackupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AerospikeBackup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AerospikeBackupList.
func (in *AerospikeBackupList) DeepCopy() *AerospikeBackupList {
	if in == nil {
		return nil
	}
	out := new(AerospikeBackupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AerospikeBackupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AerospikeBackupService) DeepCopyInto(out *AerospikeBackupService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AerospikeBackupService.
func (in *AerospikeBackupService) DeepCopy() *AerospikeBackupService {
	if in == nil {
		return nil
	}
	out := new(AerospikeBackupService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AerospikeBackupService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AerospikeBackupServiceList) DeepCopyInto(out *AerospikeBackupServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AerospikeBackupService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AerospikeBackupServiceList.
func (in *AerospikeBackupServiceList) DeepCopy() *AerospikeBackupServiceList {
	if in == nil {
		return nil
	}
	out := new(AerospikeBackupServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AerospikeBackupServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AerospikeBackupServiceSpec) DeepCopyInto(out *AerospikeBackupServiceSpec) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
	in.PodSpec.DeepCopyInto(&out.PodSpec)
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.SecretMounts != nil {
		in, out := &in.SecretMounts, &out.SecretMounts
		*out = make([]SecretMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(Service)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AerospikeBackupServiceSpec.
func (in *AerospikeBackupServiceSpec) DeepCopy() *AerospikeBackupServiceSpec {
	if in == nil {
		return nil
	}
	out := new(AerospikeBackupServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AerospikeBackupServiceStatus) DeepCopyInto(out *AerospikeBackupServiceStatus) {
	*out = *in
	in.Config.DeepCopyInto(&out.Config)
	in.PodSpec.DeepCopyInto(&out.PodSpec)
	if in.SecretMounts != nil {
		in, out := &in.SecretMounts, &out.SecretMounts
		*out = make([]SecretMount, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(Service)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AerospikeBackupServiceStatus.
func (in *AerospikeBackupServiceStatus) DeepCopy() *AerospikeBackupServiceStatus {
	if in == nil {
		return nil
	}
	out := new(AerospikeBackupServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AerospikeBackupSpec) DeepCopyInto(out *AerospikeBackupSpec) {
	*out = *in
	out.BackupService = in.BackupService
	in.Config.DeepCopyInto(&out.Config)
	if in.OnDemandBackups != nil {
		in, out := &in.OnDemandBackups, &out.OnDemandBackups
		*out = make([]OnDemandBackupSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AerospikeBackupSpec.
func (in *AerospikeBackupSpec) DeepCopy() *AerospikeBackupSpec {
	if in == nil {
		return nil
	}
	out := new(AerospikeBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AerospikeBackupStatus) DeepCopyInto(out *AerospikeBackupStatus) {
	*out = *in
	out.BackupService = in.BackupService
	in.Config.DeepCopyInto(&out.Config)
	if in.OnDemandBackups != nil {
		in, out := &in.OnDemandBackups, &out.OnDemandBackups
		*out = make([]OnDemandBackupSpec, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AerospikeBackupStatus.
func (in *AerospikeBackupStatus) DeepCopy() *AerospikeBackupStatus {
	if in == nil {
		return nil
	}
	out := new(AerospikeBackupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AerospikeRestore) DeepCopyInto(out *AerospikeRestore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AerospikeRestore.
func (in *AerospikeRestore) DeepCopy() *AerospikeRestore {
	if in == nil {
		return nil
	}
	out := new(AerospikeRestore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AerospikeRestore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AerospikeRestoreList) DeepCopyInto(out *AerospikeRestoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AerospikeRestore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AerospikeRestoreList.
func (in *AerospikeRestoreList) DeepCopy() *AerospikeRestoreList {
	if in == nil {
		return nil
	}
	out := new(AerospikeRestoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AerospikeRestoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AerospikeRestoreSpec) DeepCopyInto(out *AerospikeRestoreSpec) {
	*out = *in
	out.BackupService = in.BackupService
	in.Config.DeepCopyInto(&out.Config)
	out.PollingPeriod = in.PollingPeriod
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AerospikeRestoreSpec.
func (in *AerospikeRestoreSpec) DeepCopy() *AerospikeRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(AerospikeRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AerospikeRestoreStatus) DeepCopyInto(out *AerospikeRestoreStatus) {
	*out = *in
	if in.JobID != nil {
		in, out := &in.JobID, &out.JobID
		*out = new(int64)
		**out = **in
	}
	in.RestoreResult.DeepCopyInto(&out.RestoreResult)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AerospikeRestoreStatus.
func (in *AerospikeRestoreStatus) DeepCopy() *AerospikeRestoreStatus {
	if in == nil {
		return nil
	}
	out := new(AerospikeRestoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupService) DeepCopyInto(out *BackupService) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupService.
func (in *BackupService) DeepCopy() *BackupService {
	if in == nil {
		return nil
	}
	out := new(BackupService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OnDemandBackupSpec) DeepCopyInto(out *OnDemandBackupSpec) {
	*out = *in
	out.Delay = in.Delay
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OnDemandBackupSpec.
func (in *OnDemandBackupSpec) DeepCopy() *OnDemandBackupSpec {
	if in == nil {
		return nil
	}
	out := new(OnDemandBackupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretMount) DeepCopyInto(out *SecretMount) {
	*out = *in
	in.VolumeMount.DeepCopyInto(&out.VolumeMount)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretMount.
func (in *SecretMount) DeepCopy() *SecretMount {
	if in == nil {
		return nil
	}
	out := new(SecretMount)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Service) DeepCopyInto(out *Service) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Service.
func (in *Service) DeepCopy() *Service {
	if in == nil {
		return nil
	}
	out := new(Service)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceContainerSpec) DeepCopyInto(out *ServiceContainerSpec) {
	*out = *in
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(v1.SecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceContainerSpec.
func (in *ServiceContainerSpec) DeepCopy() *ServiceContainerSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceContainerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServicePodSpec) DeepCopyInto(out *ServicePodSpec) {
	*out = *in
	in.ServiceContainerSpec.DeepCopyInto(&out.ServiceContainerSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServicePodSpec.
func (in *ServicePodSpec) DeepCopy() *ServicePodSpec {
	if in == nil {
		return nil
	}
	out := new(ServicePodSpec)
	in.DeepCopyInto(out)
	return out
}
