# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/asdb.aerospike.com_aerospikeclusters.yaml
- bases/asdb.aerospike.com_aerospikebackups.yaml
- bases/asdb.aerospike.com_aerospikerestores.yaml
- bases/asdb.aerospike.com_aerospikebackupservices.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_aerospikeclusters.yaml
#- patches/webhook_in_aerospikebackups.yaml
#- patches/webhook_in_aerospikerestores.yaml
#- patches/webhook_in_aerospikebackupservices.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_aerospikeclusters.yaml
#- patches/cainjection_in_aerospikebackups.yaml
#- patches/cainjection_in_aerospikerestores.yaml
#- patches/cainjection_in_aerospikebackupservices.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
