apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: aerospike-monitoring-stack-alertmanager
  namespace: monitoring
  labels:
    app: aerospike-monitoring-stack-alertmanager
    chart: aerospike-monitoring-stack
    release: aerospike-monitoring-stack
    app.kubernetes.io/component: aerospike-alertmanager
    unique-app: aerospike-monitoring-stack-alertmanager
spec:
  selector: {}
  template:
    spec:
      containers:
        - name: alertmanager
          image: prom/alertmanager:latest
          args:
            - --config.file=/etc/alertmanager/alertmanager.yml
            - --storage.path=/alertmanager
            - --log.level=info
            - --cluster.advertise-address=0.0.0.0:9093
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9093
            initialDelaySeconds: 25
            periodSeconds: 20
          ports:
            - containerPort: 9093
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9093
          volumeMounts:
            - mountPath: /etc/alertmanager
              name: alertmanagerconf
            - mountPath: /alertmanager
              name: alertmanagerdata
      securityContext:
        fsGroup: 26
      serviceAccountName: aerospike-monitoring-stack
      volumes:
        - name: alertmanagerdata
          persistentVolumeClaim:
            claimName: alertmanagerdata
        - name: alertmanagerconf
          configMap:
            defaultMode: 420
            name: alertmanager-config