## Number of operator replicas
replicas: 2

## Operator image
operatorImage:
  repository: aerospike/aerospike-kubernetes-operator
  tag: 4.0.2
  pullPolicy: IfNotPresent

## In case the above image is pulled from a registry that requires
## authentication, a secret containing credentials can be added
## imagePullSecrets:
##   - secret_with_credentials_to_custom_registry
imagePullSecrets: {}

## Create RBAC resources
rbac:
  create: true
  # serviceAccountName: "default"

## Ports
healthPort: 8081
metricsPort: 8443

## Create certificates
certs:
  webhook:
    create: true
    webhookServerCertSecretName: "webhook-server-cert"
  metrics:
    create: false
    metricsServerCertSecretName: "metrics-server-cert"

##  Operator configurations
watchNamespaces: "default,aerospike"

# Registry used to pull aerospike-init image
aerospikeKubernetesInitRegistry: "docker.io"

# Namespace in registry used to pull aerospike-init image
aerospikeKubernetesInitRegistryNamespace: "aerospike"

# Name and tag of aerospike-init image
aerospikeKubernetesInitNameTag: "aerospike-kubernetes-init:2.3.0-dev3"

## Resources - limits / requests
resources:
  limits:
    cpu: 400m
    memory: 512Mi
  requests:
    cpu: 10m
    memory: 64Mi

## Affinity rules
affinity: {}
  # nodeAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: kubernetes.io/hostname
  #         operator: In
  #         values:
  #         - <Kubernetes Host>

## Extra environment variables that will be passed into the operator pods
extraEnv: {}

## Node selector
nodeSelector: {}

## Tolerations
tolerations: []

## Deployment annotations and labels
## Deployment labels are inherited by the pods automatically
annotations: {}
labels: {}

## Pod annotations and labels
podAnnotations: {}
podLabels: {}

## Service configuration
metricsService:
  # labels: {}
  # annotations: {}
  port: 8443
  type: ClusterIP

webhookService:
  # labels: {}
  # annotations: {}
  port: 443
  targetPort: 9443
  type: ClusterIP

## Pod security context
podSecurityContext: {}

## Container security context
securityContext:
  allowPrivilegeEscalation: false

livenessProbe:
   initialDelaySeconds: 15
   periodSeconds: 20
   timeoutSeconds: 1
   successThreshold: 1
   failureThreshold: 3
readinessProbe:
   initialDelaySeconds: 5
   periodSeconds: 10
   timeoutSeconds: 1
   successThreshold: 1
   failureThreshold: 3