## Number of operator replicas
replicas: 2

## Operator image
operatorImage:
  repository: aerospike/aerospike-kubernetes-operator
  tag: 3.0.0
  pullPolicy: IfNotPresent

## In case the above image is pulled from a registry that requires
## authentication, a secret containining credentials can be added
## imagePullSecrets:
##   - secret_with_credentials_to_custom_registry
imagePullSecrets: {}

## Create RBAC resources
rbac:
  create: true
  # serviceAccountName: "default"

## Ports
healthPort: 8081
metricsPort: 8080

## Create certificates
certs:
  create: true
  webhookServerCertSecretName: "webhook-server-cert"

##  Operator configurations
watchNamespaces: "default"

# Registry used to pull aerospike-init image
aerospikeKubernetesInitRegistry: "docker.io"

## Resources - limits / requests
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 10m
    memory: 64Mi

## Affinity rules
affinity: {}
  # nodeAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: kubernetes.io/hostname
  #         operator: In
  #         values:
  #         - <Kubernetes Host>

## Extra environment variables that will be passed into the operator pods
extraEnv: {}

## Node selector
nodeSelector: {}

## Tolerations
tolerations: []

## Deployment annotations and labels
## Deployment labels are inherited by the pods automatically
annotations: {}
labels: {}

## Pod annotations and labels
podAnnotations: {}
podLabels: {}

## Service configuration
metricsService:
  # labels: {}
  # annotations: {}
  port: 8443
  type: ClusterIP

webhookService:
  # labels: {}
  # annotations: {}
  port: 443
  targetPort: 9443
  type: ClusterIP

## Pod security context
podSecurityContext: {}

## Container security context
securityContext:
  allowPrivilegeEscalation: false

livenessProbe:
   initialDelaySeconds: 15
   periodSeconds: 20
   timeoutSeconds: 1
   successThreshold: 1
   failureThreshold: 3
readinessProbe:
   initialDelaySeconds: 5
   periodSeconds: 10
   timeoutSeconds: 1
   successThreshold: 1
   failureThreshold: 3

# Kube RBAC Proxy sidecar
kubeRBACProxy:
  image:
    repository: gcr.io/kubebuilder/kube-rbac-proxy
    tag: v0.13.1
    pullPolicy: IfNotPresent
  port: 8443
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 5m
      memory: 64Mi