# These resources constitute the fully configured set of manifests
# used to generate the 'manifests/' directory in a bundle.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bases/
  - rbac/
  - ../default
  - ../samples
  - ../scorecard
