apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

labels:
  - includeSelectors: false
    pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: aerospike-monitoring-stack

namePrefix: aerospike-monitoring-stack-

resources:
  - grafana
  - prometheus
  - alertmanager