apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: aerospike-monitoring
      vendor: aerospike

resources:
  - grafana
  - prometheus
  - alertmanager