apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: aerospike-monitoring-stack-prometheus
subjects:
  - kind: ServiceAccount
    name: aerospike-monitoring-stack-prometheus
    namespace: monitoring