apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: aerospike-monitoring-stack
    chart: aerospike-monitoring-stack
    release: aerospike-monitoring-stack
  name: aerospike-monitoring-stack
  namespace: default