kind: Service
apiVersion: v1
metadata:
  name: aerospike-monitoring-stack-prometheus
spec:
  ports:
    - name: http
      port: 9090
      protocol: TCP
      targetPort: 9090
  sessionAffinity: ClientIP