apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: aerospike-monitoring-stack-prometheus
  namespace: default
  labels: &Labels
    app: aerospike-monitoring-stack-prometheus
    chart: aerospike-monitoring-stack
    release: aerospike-monitoring-stack
    app.kubernetes.io/component: prometheus
    unique-app: aerospike-monitoring-stack-prometheus
spec:
  serviceName: aerospike-monitoring-stack-prometheus
  replicas: 1
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels: *Labels
  template:
    metadata:
      labels: *Labels
      annotations:
    spec:
      serviceAccountName: aerospike-monitoring-stack
      containers:
        - name: prometheus-server
          image: "prom/prometheus:latest"
          imagePullPolicy: "IfNotPresent"
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.path=/data
            - --web.listen-address=:9090
          ports:
            - containerPort: 9090
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9090
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9090
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          resources:
            {}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/prometheus
            - name: "prometheus-data"
              mountPath: /data
            - mountPath: /etc/prometheus/alert-rules.d
              name: alertmanagerrules
      terminationGracePeriodSeconds: 120
      securityContext:
        fsGroup: 65534
      volumes:
        - name: config-volume
          configMap:
            name: aerospike-monitoring-stack-prometheus-config
        - name: "prometheus-data"
          persistentVolumeClaim:
            claimName: prometheusdata
        - name: alertmanagerrules
          configMap:
              defaultMode: 420
              name: alert-rules-config